version: '2'
services:
  db:
    image: mysql:5.6.31
    container_name: mysql-olc
    volumes:
      - /Users/kumagaitomohiro/docker/mysql/sql:/docker-entrypoint-initdb.d
      - /Users/kumagaitomohiro/docker/mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  memcached:
    image: memcached:latest
    ports:
      - "8081:11211"

